name: Metrics Languages Recent

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Languages Recent
        uses: oseconds/metrics@7431ea099c3caa2fe7f2c848dac848c2965fae57
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds
          filename: metrics-languages-recent.svg
          base: ""

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_recent_days: 14
