name: Metrics Languages Recent

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  metrics-recent:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Languages Recent
        uses: oseconds/metrics@master
        with:
          user: oseconds
          token: ${{ secrets.METRICS_TOKEN }}

          # Local patched version
          use_prebuilt_image: no

          # Debug
          debug: yes
          debug_print: yes

          filename: metrics-languages-recent.svg

          template: classic
          base: ""

          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes

          plugin_languages_sections: recently-used

          plugin_languages_limit: 12
          plugin_languages_details: lines,percentage

          plugin_languages_aliases: Thrift:MiniMaxH3,INI:Seedance,Kotlin:Kling

          plugin_languages_colors: markdown:#1e293b,minimaxh3:#84cc16,seedance:#ef4444,kling:#f59e0b

          # Recent languages
          plugin_languages_recent_categories: data,markup,programming
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 0

          # Analysis
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
