name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Activity
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds
    
          template: classic
          base: header, activity, metadata
          filename: profile/activity.svg
    
          config_timezone: Asia/Seoul
    
    
          plugin_lines: yes
          plugin_lines_sections: base
    
    
      - name: Topics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds
    
          template: classic
          base: ""
          filename: profile/topics.svg
    
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_limit: 12
    
    
      - name: Code
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds
    
          template: classic
          base: ""
          filename: profile/code.svg
    
          plugin_code: yes
          plugin_code_days: 30
    
    
      - name: WakaTime
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds
    
          template: classic
          base: ""
          filename: profile/wakatime.svg
    
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time,languages
