name: Metrics Languages Indepth

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  metrics-indepth:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Languages Indepth
        uses: oseconds/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: oseconds

          plugin_languages_skipped: metrics
          use_prebuilt_image: no

          debug: yes
          debug_print: yes

          filename: metrics-languages-indepth.svg

          base: ""

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used

          plugin_languages_details: lines
          plugin_languages_limit: 0
          plugin_languages_other: no
          plugin_languages_ignored: svg,html,css,json,xml,yaml,yml,Batchfile

          plugin_languages_aliases: Thrift:MiniMaxH3,INI:Seedance,Kotlin:Kling,Gherkin:GPTImage2
          plugin_languages_colors: markdown:#000671,minimaxh3:#84cc16,seedance:#ef233c,kling:#700bf5,gptimage2:#a855f7,asciidoc:#0c1119,text:#007e82
          plugin_languages_categories: programming,markup,data,prose
          plugin_languages_threshold: 0.9

          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
